version: "3.3"

services:

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: articlesapi
      POSTGRES_PASSWORD: 123
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - 5432:5432
    networks:
      - articles-api
#      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-123}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - 80:80
    networks:
      - articles-api
#      - postgres
    restart: unless-stopped

  kafka:
    container_name: kafka
    image: 'lensesio/box'
    ports:
      - 3030:3030
      - 9092:9092
    environment:
      - ADV_HOST=kafka
      - EULA=https://dl.lenses.stream/d/?id=3a672be3-7167-11ec-9ed6-42010af01003
    networks:
      - articles-api
#      - kafka
    restart: unless-stopped

  discovery:
    container_name: discovery
    build: discovery-service
    ports:
    - 8761:8761
    networks:
      - articles-api
    restart: unless-stopped

  articles:
    container_name: articles-api
    build: articles
    ports:
      - 8080:8080
    depends_on:
      - discovery
      - postgres
      - kafka
    networks:
      - articles-api
#      - postgres
#      - kafka
    restart: unless-stopped

networks:
  articles-api:
    driver: bridge
  kafka:
    driver: bridge
  postgres:
    driver: bridge

volumes:
  postgres:
  pgadmin: